name: "Setup Environment"

inputs:
  cache-key:
    description: "The key to use for caching"
    required: true
  working-directory:
    description: "The working directory to run 'npm ci'"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      shell: bash
      # package-lock.jsonを見てインストールする
      run: npm ci
      working-directory: ${{inputs.working-directory}}
