# Webhookのデプロイ
name: webhook-CD

on:
  pull_request:
    paths:
      - "webhook/**"
      - ".github/workflows/webhook-cd.yml"
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setupEnvironment
        with:
          cache-key: "webhook"
          working-directory: ./webhook

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: "3.0.1"
          workingDirectory: ./webhook
          command: deploy
          secrets: CHANNEL_SECRET
        env:
          CHANNEL_SECRET: ${{ secrets.CHANNEL_SECRET }}

      - name: Fix permissions borked by cloudflare/wrangler-action
        run: sudo chown -R $(id -un):$(id -gn) ${{ github.workspace }}
